groups/urls.py
from django.urls import path
from groups import views

app_name = 'groups'

urlpatterns = [
    path('', views.ListGroups.as_view(), name='all'),
    path('new/', views.CreateGroup.as_view(), name='create'),
    path('posts/in/<slug>/', views.SingleGroup.as_view(), name='single'),
    path('join/<slug>/', views.JoinGroup.as_view(), name='join'),
    path('leave/<slug>/', views.LeaveGroup.as_view(), name='leave')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import IndexPage, TestPage, ThanksPage

urlpatterns = [
    path('', IndexPage.as_view(), name='index'),
    path('test/', TestPage.as_view(), name='test'),
    path('thanks/', ThanksPage.as_view(), name='thanks'),

    path('admin/', admin.site.urls),

    path('site/accounts/', include('account.urls', namespace='account')),
    path('groups/', include('groups.urls', namespace='groups')),
    path('posts/', include('posts.urls', namespace='posts')),
]

posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('new/', views.CreatePost.as_view(), name='create'),
    path('by/<username>/<pk>/',views.PostDetail.as_view(),name="single"),
    path('by/<username>/', views.UserPosts.as_view(), name='for_user'),
    path('delete/<pk>/', views.DeletePost.as_view(), name='delete'),
]

groups/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.utils.text import slugify
import misaka

from django.contrib.auth import get_user_model

User = get_user_model()
# Create your models here.

from django import template
register = template.Library()

class Group(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False, default='', blank=True)

    # many to many relation between User and Group through GroupMember class
    members = models.ManyToManyField(User, through='GroupMember')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        # pass
        return reverse('groups:single', kwargs={'slug':self.slug})


    class Meta:
        ordering = ['name']



class GroupMember(models.Model):
    group = models.ForeignKey(Group, related_name='memberships', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='user_groups', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


    class Meta:
        unique_together = ('group', 'user')

groups/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import(LoginRequiredMixin, PermissionRequiredMixin)
from django.urls import reverse
from django.db import IntegrityError
from django.shortcuts import get_object_or_404
from django.views import generic
from django.contrib import messages
from groups.models import Group, GroupMember


# Create your views here.

class CreateGroup(LoginRequiredMixin, generic.CreateView):
    fields = ('name', 'description')
    model = Group


class SingleGroup(generic.DetailView):
    model = Group

class ListGroups(generic.ListView):
    model = Group


class JoinGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs={'slug':self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group, slug=self.kwargs.get('slug'))

        try:
            GroupMember.objects.create(user=self.request.user, group=group)
        except IntegrityError:
            messages.warning(self.request,('Warning, You are already a member of {}'.format(group.name)))
        else:
            messages.success(self.request,('You are now a member of the {} group.'.format(group.name)))

        return super().get(request, *args, **kwargs)


class LeaveGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs={'slug':self.kwargs.get('slug')})


    def get(self, request, *args, **kwargs):
        try:
            membership = GroupMember.objects.filter(user=self.request.user, group__slug=self.kwargs.get('slug')).get()

        except GroupMember.DoesNotExist:
            messages.warning(self.request, "You can not leave this group, because you aren't in it")

        else:
            membership.delete()
            messages.success(self.request, 'You are not member of this group, anymore')

        return super().get(request, *args, **kwargs)

groups/templates/groups/group_base.html
{% extends 'base.html' %}
{% block content %}
  <div class="container">
    <div class="row">
      {% block pregroup %} {% endblock pregroup %}
      {% block group_content %} {% endblock group_content %}
      {% block postgroup %} {% endblock postgroup %}
    </div>
  </div>

{% endblock %}

groups/templates/groups/group_detail.html
{% extends 'groups/group_base.html' %}

<!-- Pregroup Block -->

{% block pregroup %}
<h1>{{group.name}}</h1>
<h6>Member Count: {{group.members.count}}</h6>

<div class="content">
  <a href="{% url "posts:create" %}" class='btn bg-info btn-sm'>
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-circle-fill" viewBox="0 0 16 16">
      <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.5 4.5a.5.5 0 0 0-1 0v3h-3a.5.5 0 0 0 0 1h3v3a.5.5 0 0 0 1 0v-3h3a.5.5 0 0 0 0-1h-3v-3z"/>
    </svg>
    <span class="text-light icon-label">Add Post</span>
  </a>
  {% if user in group.members.all %}
    <a href="{% url 'groups:leave' slug=group.slug %}" class="btn btn-sm btn-fill btn-warning">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heartbreak-fill" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M8.931.586 7 3l1.5 4-2 3L8 15C22.534 5.396 13.757-2.21 8.931.586ZM7.358.77 5.5 3 7 7l-1.5 3 1.815 4.537C-6.533 4.96 2.685-2.467 7.358.77Z"/>
      </svg>
      <span class="text-light icon-label">Out</span></a>
  {% else %}
    <a href="{% url 'groups:join' slug=group.slug %}" class="btn btn-sm btn-fill btn-warning">
      <span class="glyphicon glyphicon-ok-circle"></span>
      Join</a>
  {% endif %}
</div>

{% endblock pregroup %}


<!-- Group Content -->

{% block group_content %}

<div class="col-md-8">
  {% if group.posts.count == 0 %}
    <h2>No posts in this group yet!</h2>
  {% else %}
    {% for post in group.posts.all %}
      {% include "posts/_post.html" with word_length="30" %}
    {% endfor %}
  {% endif %}
</div>
{% endblock group_content %}

groups/templates/groups/group_form.html
{% extends "groups/group_base.html" %}
{% load django_bootstrap5 %}

{% block group_content %}
<h4>Create A New Group</h4>
  <form method="POST" action="{% url 'groups:create' %}" id="groupForm">
  	{% csrf_token %}
  	{% bootstrap_form form %}

    {% bootstrap_button button_type="submit" content="Create" %}
  	<!-- <input type="submit" value="Create" class="btn btn-primary btn-large"> -->
  </form>
{% endblock %}

groups/templates/groups/group_list.html
{% extends 'groups/group_base.html' %}

<!-- Pregroup Block -->
{% block pregroup %}
<div class="col-md-4">
  <div class="container">
    {% if user.is_authenticated %}
    <h2> Welcome back
      <a href="#">@{{user.username}}</a>
    </h2>
    {% endif %}

    <h2> Groups </h2>
    <p>Welcome to the Group Page! Select a Group with a shared interest!</p>
  </div>

  {% if user.is_authenticated %}
    <a href="{% url 'groups:create' %}" class='btn btn-md btn-fill btn-warning'><span class="glyphicon glyphicon-plus-sign"></span> Create New Group!</a>
  {% endif %}
</div>
{% endblock pregroup %}


<!-- Group Content -->
{% block group_content %}

<div class="col-md-8">
  {% for group in group_list %}
  <div class="group-list card">
    <h3 class="card-title">
      <a href={% url 'groups:single' slug=group.slug %}>{{ group.name }}</a>
    </h3>
    <p class="card-text">{{ group.description_html|safe}}</p>

      <ul class="list-inline">
        <li class="list-inline-item"><span class="text-list badge">{{ group.members.count }}</span> member{{ group.members.count|pluralize }}</li>
        <li class="list-inline-item"><span class='text-list badge'>{{100}}</span> post{{100|pluralize}}</li>
      </ul>
  </div>
  <br>
  {% endfor %}
</div>











  <!-- <div class="col-md-8">
    <div class="list-group">
      {% for group in group_list %}
        <a class='list-group-item' href="{% url 'groups:single' slug=group.slug %}">
          <h3 class="title list-group-item-heading">{{ group.name }}</h3>
        </a>

        <div class="list-group-item-text container-fluid">
          {{ group.description_html|safe}}

          <div class="row">
            <div class="col-md-4">
              <span class="badge">{{ group.members.count }}</span> member{{ group.members.count|pluralize }}
            </div>
            <div class="col-md-4">
              <span class='badge'>{{100}}</span> post{{100|pluralize}}
            </div>
          </div> <br>
        </div>
      {% endfor %}
    </div>
  </div> -->

{% endblock group_content %}