account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from account.views import SignUp

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', SignUp.as_view(), name='signup'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import IndexPage, TestPage, ThanksPage

urlpatterns = [
    path('', IndexPage.as_view(), name='index'),
    path('test/', TestPage.as_view(), name='test'),
    path('thanks/', ThanksPage.as_view(), name='thanks'),

    path('admin/', admin.site.urls),

    path('site/accounts/', include('account.urls', namespace='account')),
    path('groups/', include('groups.urls', namespace='groups')),
    path('posts/', include('posts.urls', namespace='posts')),
]

posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('new/', views.CreatePost.as_view(), name='create'),
    path('by/<username>/<pk>/',views.PostDetail.as_view(),name="single"),
    path('by/<username>/', views.UserPosts.as_view(), name='for_user'),
    path('delete/<pk>/', views.DeletePost.as_view(), name='delete'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Social Site</title>
    {% include 'css.html' %}

    {% block css_link %}
    {% endblock %}

    {% include 'fonts_link.html'%}

  </head>
  <body>
    {% include 'navbar.html' %}
    <div class="container-fluid">
      {% block content %}
      {% endblock %}
    </div>

    <canvas id="canvas"></canvas>
    {% include 'js.html' %}
  </body>
</html>

templates/css.html
{% load static %}
<!-- bootstrap3 CDN -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css" integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'mysite/css/master.css'%}">

templates/fonts_link.html
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Pacifico&family=Padauk&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100&family=Russo+One&display=swap" rel="stylesheet">

templates/index.html
{% extends 'base.html' %}
{% block content %}
<h1>Welcome to Social Site!</h1>

{% endblock %}

templates/js.html
{% load static %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<script src="{% static "mysite/js/master.js"%}" type="text/javascript" ></script>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand {% if request.path == home_url %} active {% endif %}" href="{% url 'index' %}"><span style="font-family: 'Pacifico', cursive; color:#ffb01f;">SoS</span> <span style="font-family: 'Pacifico', cursive;font-family: 'Padauk', sans-serif;"></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      {% if user.is_authenticated %}
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link {% if request.path == home_url %} active {% endif %}" aria-current="page" href="{% url 'posts:all'%}">Post</a>
          </li>
          <!-- <li class="nav-item">
            <a class="nav-link" href="#">Groups</a>
          </li> -->
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Groups
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item {% if request.path == home_url %} active {% endif %}" href="{% url 'groups:all' %}">Group List</a></li>
              <li><a class="dropdown-item {% if request.path == home_url %} active {% endif %}" href="{% url 'groups:create' %}">Create One</a></li>
              <!-- <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li> -->
            </ul>
          </li>
          <!-- <li class="nav-item">
            <a class="nav-link disabled">Disabled</a>
          </li> -->
        </ul>
        <li class="nav-item">
          <a class="nav-link {% if request.path == home_url %} active {% endif %}" aria-current="page" href="{% url 'account:logout' %}">Logout</a>
        </li>
      {% else %}
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link {% if request.path == home_url %} active {% endif %}" aria-current="page" href="{% url 'posts:all' %}">Post</a>
        </li>
        <!-- <li class="nav-item">
          <a class="nav-link" href="#">Groups</a>
        </li> -->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Groups
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item {% if request.path == home_url %} active {% endif %}" href="#">Group List</a></li>
            <!-- <li><a class="dropdown-item" href="#">New Post</a></li> -->
            <!-- <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li> -->
          </ul>
        </li>
        <!-- <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li> -->
        <!-- <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Registration</a>
        </li>
      </ul> -->
      {% endif %}
      <form class="d-flex ">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
      {% if not user.is_authenticated %}
        <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">
          <li class="nav-item">
            <a class="nav-link {% if request.path == home_url %} active {% endif %}" aria-current="page" href="{% url 'account:login' %}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.path == home_url %} active {% endif %}" aria-current="page" href="{% url 'account:signup' %}">Registration</a>
          </li>
        </ul>
      {% endif %}
    </div>
  </div>
</nav>

templates/test.html
{% extends 'base.html'%}

{% block content %}
  <h2>This is test page!</h2>
{% endblock %}

templates/thanks.html
{% extends 'base.html'%}

{% block content %}
  <h2>This is thank page!</h2>
{% endblock %}