mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import IndexPage, TestPage, ThanksPage

urlpatterns = [
    path('', IndexPage.as_view(), name='index'),
    path('test/', TestPage.as_view(), name='test'),
    path('thanks/', ThanksPage.as_view(), name='thanks'),

    path('admin/', admin.site.urls),

    path('site/accounts/', include('account.urls', namespace='account')),
    path('groups/', include('groups.urls', namespace='groups')),
    path('posts/', include('posts.urls', namespace='posts')),
]

posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('new/', views.CreatePost.as_view(), name='create'),
    path('by/<username>/<pk>/',views.PostDetail.as_view(),name="single"),
    path('by/<username>/', views.UserPosts.as_view(), name='for_user'),
    path('delete/<pk>/', views.DeletePost.as_view(), name='delete'),
]

posts/models.py
import misaka
from django.db import models
from django.urls import reverse
from django.conf import settings
from groups.models import Group
from django.contrib.auth import get_user_model

User = get_user_model()


# Create your models here.
class Post(models.Model):
    user = models.ForeignKey(User, related_name='posts', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    group = models.ForeignKey(Group, related_name='posts', null=True, on_delete=models.CASCADE, blank=True)


    def __str__(self):
        return self.message


    def save(self,*args, **kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("posts:single", kwargs={'username':self.user.username,'pk':self.pk})

    class Meta:
        ordering = ['-created_at']
        unique_together=['user', 'message']

posts/forms.py
from django import forms
from posts.models import Post
from groups.models import Group

class PostForm(forms.ModelForm):
    class Meta:
        fields = ('message', 'group')
        model = Post

    def __init__(self, *args, **kwargs):

        super().__init__(*args, **kwargs)
        user = kwargs['initial'].get('user', None)


        if user is not None:
            self.fields['group'].queryset = Group.objects.filter(memberships__user=user)

posts/views.py
from django.shortcuts import render
from django.contrib import messages
from django.urls import reverse_lazy
from django.urls import reverse
from django.http import Http404
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from braces.views import SelectRelatedMixin

from posts.forms import PostForm
from posts.models import Post
from groups.models import Group

from django.contrib.auth import get_user_model
User = get_user_model()

# Create your views here.
class PostList(SelectRelatedMixin, generic.ListView):
    model = Post
    select_related = ('user', 'group')
    queryset=Post.objects.all()


    def get_context_data(self, *args, **kwargs):
        # print(f"Context: {kwargs}")
        context = super(PostList, self).get_context_data(*args,**kwargs)

        if self.request.user.is_authenticated:
            context['user_groups'] = Group.objects.filter(members__in=[self.request.user])

        context['all_groups'] = Group.objects.all()


        return context

class UserPosts(generic.ListView):
    model = Post
    template_name = 'posts/user_post_list.html'

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related("posts").get(username__iexact=self.kwargs.get('username'))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post_user'] = self.post.user
        return context



class PostDetail(SelectRelatedMixin, generic.DetailView):
    model = Post
    select_related = ('user', 'group')


    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact=self.kwargs.get('username'))


class CreatePost(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    # fields = ('message', 'group')
    model = Post
    form_class = PostForm


    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        print("%"*10)
        context['group'] = Group.objects.filter(memberships__user=self.request.user)
        # context['group']=context['user_group'][0]
        print(f"Context:{context}")
        return context

        ## Send user argument to the form.py file
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['initial']['user'] = self.request.user
        return kwargs



class DeletePost(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = Post
    select_related = ('user', 'group')
    # success_url = reverse_lazy('posts:all')


    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, "Post has been deleted!")
        return super().delete(*args, **kwargs)

    def get_success_url(self, *args, **kwargs):
        return reverse('posts:for_user', kwargs = {'username': self.request.user})

posts/templates/posts/_post.html
{% load my_extras %}

<div class="media">
  <img src="..." class="align-self-start mr-3" alt="...">
  <div class="media-body">
    <h5 class="mt-0"><strong>{{ post.user.username }}</strong></h5>
    <small class="mt-0">
      <span class="username">
      <a href="{% url 'posts:for_user' username=post.user.username %}">@{{ post.user.username }}</a>
      </span>
    </small>
    <p>
      <time class="time">
        <a href="{% url 'posts:single' username=post.user.username pk=post.pk %}">{{ post.created_at }}</a>
      </time>

      <strong>
        {% if post.group %}
        <span class='group-name'>in <a href="{% url 'groups:single' slug=post.group.slug %}">{{ post.group.name }}</a></span>
        {% endif %}
      </strong>
    </p>

    {% if word_length|convert_int > 0 %}

      <p>{{post.message_html|word_length:'30'|safe}} <a href="{% url 'posts:single' username=post.user pk=post.pk %}"> read more</a></p>
    {% else %}
      <div class="float-end">
        {% if user.is_authenticated and post.user == user and not hide_delete %}
        <a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn bg-light btn-sm">
          <svg style="color:red;"  xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-exclamation-triangle" viewBox="0 0 16 16">
            <path d="M7.938 2.016A.13.13 0 0 1 8.002 2a.13.13 0 0 1 .063.016.146.146 0 0 1 .054.057l6.857 11.667c.036.06.035.124.002.183a.163.163 0 0 1-.054.06.116.116 0 0 1-.066.017H1.146a.115.115 0 0 1-.066-.017.163.163 0 0 1-.054-.06.176.176 0 0 1 .002-.183L7.884 2.073a.147.147 0 0 1 .054-.057zm1.044-.45a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566z"/>
            <path d="M7.002 12a1 1 0 1 1 2 0 1 1 0 0 1-2 0zM7.1 5.995a.905.905 0 1 1 1.8 0l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995z"/>
          </svg>
          <span class="text-light icon-label"></span>
        </a>

        <a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn bg-light btn-sm">
          <svg style="color:black;" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pen" viewBox="0 0 16 16">
            <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001zm-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708l-1.585-1.585z"/>
          </svg>
          <span class="text-light icon-label"></span>
        </a>
        {% endif %}
      </div>
      <hr>
      <p>{{post.message_html|safe}}</p>
    {% endif %}
  </div>
</div>

posts/templates/posts/post_base.html
{% extends 'base.html' %}

{% block content %}
  <div class="posts-page">
    <div class="container">
      <div class="row">
        {% block prepost %} {% endblock prepost %}
        {% block post_content %} {% endblock post_content %}
        {% block post_post %} {% endblock post_post %}
      </div>
    </div>

  </div>
{% endblock %}

posts/templates/posts/post_confirm_delete.html
{% extends 'posts/post_base.html' %}
{% load django_bootstrap5 %}

{% block post_content %}
  <h3>Do you want to delete the post?</h3>

  <div class="posts">
    {% include 'posts/_post.html' with post=object hide_delete=True%}
  </div><!--.posts-->

  <form method="post">

    {% csrf_token %}
    <input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
  	<a href="{% url 'posts:single' username=user.username pk=object.pk %}" class="btn btn-simple btn-large btn-light">Cancel</a>
  </form>
{% endblock post_content %}

posts/templates/posts/post_detail.html
{% extends 'posts/post_base.html' %}

{% block post_content %}
  <div class="col-md-8">
    {% include 'posts/_post.html' %}
  </div>
{% endblock post_content %}

posts/templates/posts/post_form.html
{% extends 'posts/post_base.html' %}
{% load django_bootstrap5 %}

{% block post_content %}
<h4>Create New Post</h4>
<form id="postForm" action="{% url 'posts:create' %}" method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}

  {% bootstrap_button button_type="submit" content="Post" %}
</form>

{% endblock post_content %}

posts/templates/posts/post_list.html
{% extends 'posts/post_base.html' %}
{% load humanize %}
{% load static %}
{% load my_extras %}

{% block prepost%}
  <div class="group-list col-md-4">
    {% if request.user.is_authenticated %}
    <div class="card card-with-shadow">
      <div class="content">
        <h5 class='title text-list'>Your Groups</h5>
        <ul class='list-unstyled'>
            {% for member_group in user_groups %}
            <li class='text-list group li-with-bullet'>
              <a href="{% url 'groups:single' slug=member_group.slug%}">{{member_group.name}}</a>
            </li>
            {% endfor %}
        </ul>
      </div>
    </div>
    {% endif %}

    <div class="group-list card card-with-shadow">
      <div class="content">
        <h5 class='title text-list'>All Groups</h5>
        <ul class='list-unstyled'>
          {% for other_groups in all_groups %}
            <li class='group li-with-bullet'>
              <a href="{% url 'groups:single' slug=other_groups.slug %}">{{other_groups.name}}</a>
            </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
{% endblock prepost%}

{% block post_content %}
<div class="col-md-8">
  {% for post in post_list %}
    {% include "posts/_post.html" with word_length="30" %}
  {% endfor %}
</div>
{% endblock post_content %}

posts/templates/posts/user_post_list.html
{% extends 'posts/post_base.html' %}

{% block prepost %}
<div class="col-md-4">
  <h1>@{{ post_user.username }}</h1>
  <p>Post History</p>
</div>
{% endblock %}


{% block post_content %}
<div class="col-md-8">
  {% for post in post_list %}
    {% include 'posts/_post.html' %}
  {% endfor %}
</div>
{% endblock post_content %}